### ISSUE TITLE
Need Help !

### ISSUE THREAD

**Issue by Hannibal046** [FadedCosine/kNN-KD#1]
Hi, thanks for the great work !  When trying to replicate the results on `iwslt14.de-en` you reported, I encountered the following problems. Your kind help will be much appreciated !
##  data preprocessing:
 - because the [link](https://wit3.fbk.eu/archive/2014-01/texts/de/en/de-en.tgz) in your `fairseq/examples/transaltion/prepare-iwslt14.sh` is dead. So I follow the latest `fairseq`  to download the IWSLT14.DE-EN. And by preprocessing the data with `fairseq-preprocess`, the tokens I got is **3949114** while yours is **3949106.** 

The command I use is 
 ```shell
TEXT=iwslt14.tokenized.de-en
fairseq-preprocess --source-lang de --target-lang en \
    --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
    --joined-dictionary \
    --destdir data-bin/iwslt14.tokenized.de-en \
    --workers 20
``` 
The result I got is :
```shell
[de] Dictionary: 10152 types
[de] /project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/train.de: 160239 sents, 4035591 tokens, 0.0% replaced by <unk>
[de] Dictionary: 10152 types
[de] /project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/valid.de: 7283 sents, 182592 tokens, 0.0% replaced by <unk>
[de] Dictionary: 10152 types
[de] /project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/test.de: 6750 sents, 161838 tokens, 0.029% replaced by <unk>
[en] Dictionary: 10152 types
[en]/project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/train.en: 160239 sents, 3949114 tokens, 0.0% replaced by <unk>
[en] Dictionary: 10152 types
[en]/project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/valid.en: 7283 sents, 178622 tokens, 0.00056% replaced by <unk>
[en] Dictionary: 10152 types
[en]/project/kNN-KD/examples/translation/iwslt14.tokenized.de-en/test.en: 6750 sents, 156928 tokens, 0.00319% replaced by <unk>
Wrote preprocessed data to data-bin/joined
```
 - Also, should this be reversed ?
 https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/preprocess_data.sh#L3
## Build KNN Cache
Should the dimension be `512` for Iwslt14.de-en ?
https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/build_faiss.sh#L11

## Train KNN-KD
If `save-k` doesn't equal to knn-k, I got following mistakes:
https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/train_knnmt.sh#L13
```
2022-07-25 12:13:34 | INFO | fairseq.tasks.translation_with_stored_knnls | knntarget/iwslt14.tokenized.de-en/bs1_fp16_distances_valid_k1024.mmp doesn't exist. Set 'distances' to None
2022-07-25 12:13:34 | INFO | fairseq.tasks.translation_with_stored_knnls | knntarget/iwslt14.tokenized.de-en/bs1_knntargets_valid_k1024.mmp doesn't exist. Set 'knntargets' to None
```
```
File "/project/kNN-KD/fairseq/data/language_pair_with_knntargets_dataset.py", line 320, in __init__
    assert np.sum(self.tgt_sizes) == self.knn_distances.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

## KNN-MT inference
The comma here will cause a problem in the resolve function.
https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/vanilla_knn_mt_inference.sh#L11-L13

https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/experimental_generate.py#L85

## Result
After all the revision (from my personal view), I got following results:
```
For Iwslt14.de-en:
BaseMT: 34.77
KNN-MT: 35.46 ( the hyper parameter is as suggested )
KNN-KD: 34.62 
```

I don't know where the problem is. Could you please help me out ? A complete guid for `Iwslt14.de-en` or trained checkpoint will be much appreciated !

**Comment by Hannibal046** [comment]
Also, should this be revised to `transformer_iwslt_de_en_with_datastore` ?
https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/vanilla_knn_mt_inference.sh#L18

**Comment by FadedCosine** [comment]
I am sorry for the late reply (because I will graduate soon, and I have been busy looking for a job). We provid the processed data and the checkpoints in this [link](https://drive.google.com/file/d/18aQttAT-ganzaufISmiw20BK0evHE4dS/view?usp=share_link). I wish this will solve your problems.

**Comment by FadedCosine** [comment]
> Also, should this be revised to `transformer_iwslt_de_en_with_datastore` ?
> 
> https://github.com/FadedCosine/kNN-KD/blob/72fb20cdcb31f4018ae9e3f00002fe2a542fbc80/commands/vanilla_knn_mt_inference.sh#L18

Yes, as we have stated in our paper, for iwslt datasets, we use transformer_iwslt_de_en configuration.

**Comment by robotsp** [comment]
how do you decide the value of knntarget_size? @Hannibal046 @FadedCosine

**Comment by FadedCosine** [comment]
> how do you decide the value of knntarget_size? @Hannibal046 @FadedCosine

``knntarget_size'' is the precessed token numbers. You can get this number by running ``fairseq-preprocess xxx''
