### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by BrIght-WinG-AA** [FadedCosine/kNN-KD#6]
When I run build_knntargets.sh, an error occurs with the following error message 
`ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/pytorch/lib/python3.8/site-packages/faiss/_swigfaiss.so)`

**Comment by FadedCosine** [comment]
This may seem like a faiss related error, which is often a headache issue🤕️. You can search this error info on Google and there may be corresponding solutions.

**Comment by BrIght-WinG-AA** [comment]
I've spent three days trying to troubleshoot this issue, and I'm still making no progress

**Comment by FadedCosine** [comment]
I wish you good luck🍀

**Comment by BrIght-WinG-AA** [comment]
Thank you!
